name: Update Progress Tracker

permissions:
  contents: write # <-- allow pushes via GITHUB_TOKEN

on:
  push:
    branches: [ main, master ]

jobs:
  update-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Extract last commit message
        id: commit
        run: echo "message=$(git log -1 --pretty=%B | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Update tracker
        env:
          COMMIT_MESSAGE: ${{ steps.commit.outputs.message }}
          TRACKER_PATH: progress/12-week-progress-tracker.xlsx
        run: |
          python scripts/update_tracker.py

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add progress/12-week-progress-tracker.xlsx
            git commit -m "chore: update tracker via CI"
            git push
          else
            echo "No changes to commit."
          fi
